# fly.toml app configuration file generated for soma-blog-hugo-shy-bird-7985 on 2025-10-20T15:17:48-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#


app = 'soma-blog-hugo-shy-bird-7985'
primary_region = 'dfw'

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1