baseURL = "https://soma-blog-hugo-shy-bird-7985.fly.dev/"
languageCode = "en-us"
title = "Eeshan S."
theme = "rusty-typewriter"

# Output formats for search
[outputs]
home = ["HTML", "RSS", "JSON", "SearchIndex"]

[outputFormats]
[outputFormats.SearchIndex]
baseName = "searchindex"
mediaType = "application/json"
isPlainText = true

# Content and taxonomies
[taxonomies]
tag = "tags"
category = "categories"
topic = "topics"
series = "series"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Posts"
url = "/posts/"
weight = 2

[[menu.main]]
name = "About"
url = "/about/"
weight = 3

[[menu.main]]
name = "Search"
url = "/search/"
weight = 4

[params]
description = "Deep dives into marketing analytics, experimentation, and measurement from a practitioner's perspective."
dateFormat = "January 2, 2006"

# Author information
[params.author]
name = "EeshanS"

# Links
[params.links]
theme = "https://github.com/math-queiroz/rusty-typewriter"
hugo = "https://gohugo.io/"

# Rusty Typewriter theme configuration
[params.rtwt]
sidePane = true
countPageItems = 10
searchPath = "/search"
enableDarkMode = false

[params.rtwt.home]
showBio = true
showAuthorImg = true
showFeatured = true
showRecent = true
hideRecentWhenFeatured = false
countRecent = 5

[params.rtwt.side.home]
sidePaneSticky = true
taxonomies = ["tags", "series"]
countTaxonomy = 8

[params.rtwt.side.single]
sidePaneSticky = true
showDetails = true
showTableOfContents = true
showAttachments = false
showRelated = true
countRelated = 5

[params.rtwt.side.list]
sidePaneSticky = false

# Markup configuration to allow unsafe HTML (for search functionality)
[markup.goldmark.renderer]
unsafe = true

[markup.goldmark.parser]
wrapStandAloneImageWithinParagraph = false
attribute.block = true
attribute.title = true