name: Deploy to Fly.io

on:
  push:
    branches: [main]

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      hugo: ${{ steps.filter.outputs.hugo }}
      api: ${{ steps.filter.outputs.api }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            hugo:
              - 'content/**'
              - 'static/**'
              - 'layouts/**'
              - 'themes/**'
              - 'hugo.toml'
              - 'Dockerfile'
              - 'fly.toml'
            api:
              - 'api/**'

  deploy-hugo:
    name: Deploy Hugo Site
    needs: changes
    if: needs.changes.outputs.hugo == 'true'
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: superfly/flyctl-actions/setup-flyctl@master
      
      - name: Deploy Hugo
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

  deploy-api:
    name: Deploy Python API
    needs: changes
    if: needs.changes.outputs.api == 'true'
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: superfly/flyctl-actions/setup-flyctl@master
      
      - name: Deploy API
        run: |
          cd api
          flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}